apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: NAME
  namespace: NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nifi
      cluster: NAME
  serviceName: NAME
  template:
    metadata:
      labels:
        app: nifi
        cluster: NAME
    spec:
      containers:
      - env:
        image: IMAGE
        imagePullPolicy: Always
        name: NAME-container
        ports:
        - containerPort: 8080
          name: http-port
          protocol: TCP
        - containerPort: 8443
          name: https-port
          protocol: TCP
        - containerPort: 9090
          name: prometheus-port
          protocol: TCP
        - containerPort: 9000
          name: input-port
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/ready
          failureThreshold: 3
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /tarballs
          name: tarball-volume
        - mountPath: /share
          name: share-volume
        - mountPath: /flow-xml
          name: NAME-flow-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: share-volume
        hostPath:
          path: /opt/share
      - name: tarball-volume
        hostPath:
          path: /opt/tarballs
      - configMap:
          defaultMode: 420
          items:
          - key: flow.xml
            path: flow.xml
          name: NAME
        name: NAME-flow-volume
